### ISSUE TITLE
Freeze range in Y-axis

### ISSUE THREAD

**Issue by aloboa** [ch-n/napari-time_series_plotter#33]
Even if set manually, the Y-axis range automatically resets if the cursor is moved, which makes it very difficult to compare z- profiles among pixels.
Could you add an option to freeze the y-axis range?

**Comment by Chris-N-K** [comment]
Sadly I did not find a way to keep the axis parameters set through the matplotlib interface yet, but there is the option to set the Y range in the options tab.

That should work, if not it's a bug and I have to take a look.

**Comment by aloboa** [comment]
Please see here some comments on this issue and https://github.com/Chris-N-K/napari-time-series-plotter/issues/31#issuecomment-2189520129


https://github.com/Chris-N-K/napari-time-series-plotter/assets/6074054/780e666e-b0e6-45f7-a71e-99627c9bf9f6

**Comment by aloboa** [comment]
I would say that the fact that setting the range of y-axis for one pikel z-plot does not keep fixed for the next plots is a bug. Note that the plot scale changes from pixel to pixel even if "Options/Auto scale plot axes" is not ticked.

**Comment by Chris-N-K** [comment]
Hi, I will check everything this afternoon, sorry for the wait.
From the video you showed it looks to me as if you used the matplotlib interface. That sadly doesn't persist, like I wrote above.
I will add a video showing the options tab with the Y-range fix.

**Comment by aloboa** [comment]
I have just realized the x_min, x_max, y_min, y_max fields in Options, I apologize.

**Comment by Chris-N-K** [comment]
No worries, the current implementation is far from perfect @aloboa 
Glad it works for you now.
